### ISSUE TITLE
SEGV Fault Crash autoapp 

### ISSUE THREAD

**Issue by MalHyuk** [htruong/crankshaft#633]
- What phone do you have?
Samsung A33 5G

- What OS version?
[RPI 4 B] : `Linux CRANKSHAFT-NG 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`
[Android] : `Linux localhost 5.10.136-android12-9`
[Linux] : `Ubuntu 22.04/5.19.0-43-generic`

- What crankshaft version?
`[Crankshaft OpenCarOS NG v2022.09.12.1]`

- Steps to reproduce the bug, if you're planning to report a bug. Please indicate whether the bug is always repoducible.
1. Connect USB & Bluetooth pair
Crankshaft use local bluetooth device (builtin)
![KakaoTalk_20230615_161230935](https://github.com/opencardev/crankshaft/assets/59429883/d7919331-52ca-43fe-856b-1f62bf4dc7aa)

2. Connect `AndroidBluetoothServer:5000` 
```python
from pwn import *

r = remote(crankshaft_ip , 5000)
```
![image](https://github.com/opencardev/crankshaft/assets/59429883/3f5974e4-f4c3-4455-88d9-f1a4ed1bf1dd)

![image](https://github.com/opencardev/crankshaft/assets/59429883/0e5a7c28-f4e4-4f3d-8283-098f6902f578)
[debug.zip](https://github.com/opencardev/crankshaft/files/11754323/debug.zip)

**Comment by MalHyuk** [comment]
stack backtrace

```
#0  0xa6e02418 in ?? ()
#1  0xb5468e54 in QIODevice::write(char const*, long long) () from target:/usr/local/qt5/lib/libQt5Core.so.5
#2  0x0008724c in f1x::openauto::autoapp::service::AudioService::onAVMediaWithTimestampIndication (this=this@entry=0xa6e03b2c, timestamp=<optimized out>, buffer=...) at /home/pi/prebuilts/buildsystem/openauto/src/autoapp/Service/AudioService.cpp:171
#3  0xb646d74c in f1x::aasdk::channel::av::AudioServiceChannel::handleAVMediaWithTimestampIndication (this=<optimized out>, eventHandler=..., payload=...) at /home/pi/prebuilts/buildsystem/aasdk/src/Channel/AV/AudioServiceChannel.cpp:170
#4  f1x::aasdk::channel::av::AudioServiceChannel::handleAVMediaWithTimestampIndication (this=<optimized out>, payload=..., eventHandler=...) at /home/pi/prebuilts/buildsystem/aasdk/src/Channel/AV/AudioServiceChannel.cpp:165
#5  0xb646dcf0 in f1x::aasdk::channel::av::AudioServiceChannel::messageHandler (this=0xa6e016c0, message=..., eventHandler=...) at /home/pi/prebuilts/buildsystem/aasdk/src/Channel/AV/AudioServiceChannel.cpp:98
#6  0xb646f390 in std::__invoke_impl<void, void (f1x::aasdk::channel::av::AudioServiceChannel::*&)(std::shared_ptr<f1x::aasdk::messenger::Message>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>), std::shared_ptr<f1x::aasdk::channel::av::AudioServiceChannel>&, std::shared_ptr<f1x::aasdk::messenger::Message>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>&> (__t=..., __f=<optimized out>) at /usr/include/c++/8/bits/invoke.h:73
#7  std::__invoke<void (f1x::aasdk::channel::av::AudioServiceChannel::*&)(std::shared_ptr<f1x::aasdk::messenger::Message>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>), std::shared_ptr<f1x::aasdk::channel::av::AudioServiceChannel>&, std::shared_ptr<f1x::aasdk::messenger::Message>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>&> (__fn=<optimized out>) at /usr/include/c++/8/bits/invoke.h:95
#8  std::_Bind<void (f1x::aasdk::channel::av::AudioServiceChannel::*(std::shared_ptr<f1x::aasdk::channel::av::AudioServiceChannel>, std::_Placeholder<1>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>))(std::shared_ptr<f1x::aasdk::messenger::Message>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>)>::__call<void, std::shared_ptr<f1x::aasdk::messenger::Message>&&, 0u, 1u, 2u>(std::tuple<std::shared_ptr<f1x::aasdk::messenger::Message>&&>&&, std::_Index_tuple<0u, 1u, 2u>) (__args=..., this=<optimized out>) at /usr/include/c++/8/functional:400
#9  std::_Bind<void (f1x::aasdk::channel::av::AudioServiceChannel::*(std::shared_ptr<f1x::aasdk::channel::av::AudioServiceChannel>, std::_Placeholder<1>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>))(std::shared_ptr<f1x::aasdk::messenger::Message>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>)>::operator()<std::shared_ptr<f1x::aasdk::messenger::Message>, void>(std::shared_ptr<f1x::aasdk::messenger::Message>&&) (this=<optimized out>) at /usr/include/c++/8/functional:484
#10 std::_Function_handler<void (std::shared_ptr<f1x::aasdk::messenger::Message>), std::_Bind<void (f1x::aasdk::channel::av::AudioServiceChannel::*(std::shared_ptr<f1x::aasdk::channel::av::AudioServiceChannel>, std::_Placeholder<1>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>))(std::shared_ptr<f1x::aasdk::messenger::Message>, std::shared_ptr<f1x::aasdk::channel::av::IAudioServiceChannelEventHandler>)> >::_M_invoke(std::_Any_data const&, std::shared_ptr<f1x::aasdk::messenger::Message>&&) (__functor=..., __args#0=...) at /usr/include/c++/8/bits/std_function.h:297
#11 0xb6492fb0 in std::function<void (std::shared_ptr<f1x::aasdk::messenger::Message>)>::operator()(std::shared_ptr<f1x::aasdk::messenger::Message>) const (__args#0=..., this=0xae7fac50) at /usr/include/c++/8/bits/std_function.h:687
#12 f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}::operator()() (this=0xae7fac48) at /home/pi/prebuilts/buildsystem/aasdk/include/f1x/aasdk/IO/Promise.hpp:80
#13 boost::asio::asio_handler_invoke<f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}>(f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}&, ...) (function=...) at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#14 boost_asio_handler_invoke_helpers::invoke<f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}, f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}>(f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}&, f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}&) (context=..., function=...) at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#15 boost::asio::detail::handler_work<f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}, boost::asio::system_executor>::complete<f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}>(f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}&, f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}&) (this=<synthetic pointer>, handler=..., function=...) at /usr/include/boost/asio/detail/handler_work.hpp:82
#16 boost::asio::detail::completion_handler<f1x::aasdk::io::Promise<std::shared_ptr<f1x::aasdk::messenger::Message>, f1x::aasdk::error::Error>::resolve(std::shared_ptr<f1x::aasdk::messenger::Message>)::{lambda()#1}>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned int) (owner=owner@entry=0x172bf30, base=0xa3e146b0) at /usr/include/boost/asio/detail/completion_handler.hpp:70
#17 0x00042170 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=0x0, ec=..., owner=0x172bf30, this=<optimized out>) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#18 boost::asio::detail::strand_service::do_complete (owner=owner@entry=0x172bf30, base=base@entry=0xa6e03300, ec=...) at /usr/include/boost/asio/detail/impl/strand_service.ipp:168
#19 0x001244d4 in boost::asio::detail::scheduler_operation::complete (bytes_transferred=<optimized out>, ec=..., owner=0x172bf30, this=0xa6e03300) at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#20 boost::asio::detail::scheduler::do_run_one (ec=..., this_thread=..., lock=..., this=0x172bf30) at /usr/include/boost/asio/detail/impl/scheduler.ipp:401
#21 boost::asio::detail::scheduler::run (ec=..., this=0x172bf30) at /usr/include/boost/asio/detail/impl/scheduler.ipp:154
#22 boost::asio::io_context::run (this=<optimized out>) at /usr/include/boost/asio/impl/io_context.ipp:62
#23 <lambda()>::operator() (__closure=<optimized out>) at /home/pi/prebuilts/buildsystem/openauto/src/autoapp/autoapp.cpp:65
#24 std::__invoke_impl<void, startIOServiceWorkers(boost::asio::io_service&, ThreadPool&)::<lambda()> > (__f=...) at /usr/include/c++/8/bits/invoke.h:60
#25 std::__invoke<startIOServiceWorkers(boost::asio::io_service&, ThreadPool&)::<lambda()> > (__fn=...) at /usr/include/c++/8/bits/invoke.h:95
#26 std::thread::_Invoker<std::tuple<startIOServiceWorkers(boost::asio::io_service&, ThreadPool&)::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/include/c++/8/thread:244
#27 std::thread::_Invoker<std::tuple<startIOServiceWorkers(boost::asio::io_service&, ThreadPool&)::<lambda()> > >::operator() (this=<optimized out>) at /usr/include/c++/8/thread:253
#28 std::thread::_State_impl<std::thread::_Invoker<std::tuple<startIOServiceWorkers(boost::asio::io_service&, ThreadPool&)::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /usr/include/c++/8/thread:196
#29 0xb522b9b0 in ?? () from target:/lib/arm-linux-gnueabihf/libstdc++.so.6
#30 0xb6c91494 in start_thread (arg=0xae7fb340) at pthread_create.c:486
#31 0xb5068dd8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from target:/lib/arm-linux-gnueabihf/libc.so.6
```
